# Generated by Django 5.2.15 on 2026-06-14 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price_sgd", models.DecimalField(decimal_places=2, max_digits=8)),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                ("is_available", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_by_admin", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="accounts.restaurantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "menu_items",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("RICE", "Rice"),
                            ("NOODLES", "Noodles"),
                            ("BREAD", "Bread"),
                            ("SNACKS", "Snacks"),
                            ("DRINKS", "Drinks"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(default="pack", max_length=20)),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                ("quantity_original", models.IntegerField()),
                ("quantity_available", models.IntegerField()),
                ("quantity_claimed", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("PARTIALLY_CLAIMED", "Partially Claimed"),
                            ("FULLY_CLAIMED", "Fully Claimed"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "list_status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("PAST", "Past"), ("INACTIVE", "Inactive")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("pickup_start", models.DateTimeField()),
                ("pickup_end", models.DateTimeField()),
                ("food_qr_data", models.CharField(blank=True, max_length=200)),
                ("food_qr_image_url", models.URLField(blank=True, max_length=500)),
                (
                    "sponsorship_type",
                    models.CharField(
                        choices=[
                            ("DIRECT", "Direct"),
                            ("SPONSORED_NAMED", "Sponsored Named"),
                            ("SPONSORED_ANONYMOUS", "Sponsored Anonymous"),
                        ],
                        default="DIRECT",
                        max_length=20,
                    ),
                ),
                ("sponsor_display_name", models.CharField(blank=True, max_length=100)),
                ("meal_order_id", models.UUIDField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANUAL", "Manual"),
                            ("EXPIRED", "Expired"),
                            ("FULLY_CLAIMED", "Fully Claimed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "individual_donor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_food_items",
                        to="accounts.donorprofile",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_items",
                        to="accounts.restaurantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "food_items",
                "indexes": [
                    models.Index(
                        fields=["list_status", "pickup_end"], name="food_items_list_st_2404ec_idx"
                    ),
                    models.Index(
                        fields=["restaurant", "list_status"], name="food_items_restaur_90b8d1_idx"
                    ),
                ],
            },
        ),
    ]
