# Generated by Django 5.2.15 on 2026-06-29 11:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_receiver_location"),
        ("donations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("UNSAFE_OR_SPOILED", "Food was unsafe or spoiled"),
                            ("MISLEADING_LISTING", "Listing is misleading"),
                            ("RESTAURANT_CLOSED", "Restaurant was closed or absent"),
                            ("RUDE_BEHAVIOUR", "Rude or inappropriate behaviour"),
                            ("ASKED_TO_PAY", "Asked me to pay for the food"),
                            ("OTHER", "Something else"),
                        ],
                        max_length=40,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="donations.fooditem",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_reports",
                        to="accounts.restaurantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "food_reports",
                "indexes": [
                    models.Index(
                        fields=["restaurant", "created_at"], name="food_report_restaur_cdf41b_idx"
                    ),
                    models.Index(
                        fields=["food_item", "created_at"], name="food_report_food_it_498329_idx"
                    ),
                    models.Index(
                        fields=["reporter", "created_at"], name="food_report_reporte_c43792_idx"
                    ),
                ],
            },
        ),
    ]
