# Generated by Django 5.2.15 on 2026-07-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_food_report_reason_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='recurrence_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='recurrence_type',
            field=models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('CUSTOM', 'Custom')], default='NONE', max_length=20),
        ),
    ]
