# Generated by Django 5.2.15 on 2026-07-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_fooditem_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='source_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
