# Generated by Django 5.2.15 on 2026-07-19 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_restaurant_detail_profile_gaps'),
        ('donations', '0005_restaurant_detail_profile_gaps'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo_url', models.URLField(max_length=500)),
                ('sort_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_photos', to='accounts.restaurantprofile')),
            ],
            options={
                'db_table': 'menu_photos',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['restaurant', 'sort_order'], name='menu_photos_restaur_a7d593_idx')],
            },
        ),
    ]
