# Generated by Django 5.2.15 on 2026-06-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_receiver_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiverprofile",
            name="photo_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
