# Generated by Django 5.2.15 on 2026-06-29 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_receiver_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="receiverprofile",
            name="location_services_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="receiverprofile",
            name="save_location_history",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ReceiverLocationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("place_name", models.CharField(max_length=200)),
                ("area_label", models.CharField(max_length=300)),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("FOOD_CENTRE", "Food centre"),
                            ("RESTAURANT", "Restaurant"),
                            ("SHOPPING", "Shopping"),
                            ("TRANSIT", "Transit"),
                            ("PARK", "Park"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("visited_at", models.DateTimeField()),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "receiver_location_history",
                "ordering": ["-visited_at"],
                "indexes": [
                    models.Index(
                        fields=["receiver", "visited_at"], name="receiver_lo_receive_97449c_idx"
                    )
                ],
            },
        ),
    ]
