# Generated by Django 5.2.15 on 2026-07-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_normalize_phone_e164'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='closes_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='cuisine',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='open_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='opens_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
