# Generated by Django 5.2.15 on 2026-07-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_restaurant_retention_and_export_email"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="restaurantlegalretention",
            new_name="restaurant__purge_a_84e4e7_idx",
            old_name="restaurant__purge_a_7c2e1a_idx",
        ),
        migrations.RenameIndex(
            model_name="restaurantlegalretention",
            new_name="restaurant__uen_f0a7ec_idx",
            old_name="restaurant__uen_8f1b2c_idx",
        ),
        migrations.RenameIndex(
            model_name="restaurantpayoutretention",
            new_name="restaurant__retaine_42f7d1_idx",
            old_name="restaurant__retaine_3a9d4e_idx",
        ),
        migrations.RenameIndex(
            model_name="restaurantpayoutretention",
            new_name="restaurant__former__4154ca_idx",
            old_name="restaurant__former__5b6c7d_idx",
        ),
    ]
