# Generated by Django 5.2.15 on 2026-06-14 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MealOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("total_amount_sgd", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "credit_preference",
                    models.CharField(
                        choices=[
                            ("SHOW_NAME", "Show Name"),
                            ("INITIALS", "Initials"),
                            ("ANONYMOUS", "Anonymous"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("POSTED", "Posted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_orders",
                        to="accounts.donorprofile",
                    ),
                ),
                (
                    "food_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meal_orders",
                        to="donations.fooditem",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_orders",
                        to="accounts.restaurantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "meal_orders",
            },
        ),
        migrations.CreateModel(
            name="MealOrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("unit_price_sgd", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "meal_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="donors.mealorder",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_items",
                        to="donations.menuitem",
                    ),
                ),
            ],
            options={
                "db_table": "meal_order_items",
            },
        ),
        migrations.CreateModel(
            name="MoneyDonation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("amount_sgd", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reference_code", models.CharField(max_length=20, unique=True)),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_TRANSFER", "Pending Transfer"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_TRANSFER",
                        max_length=20,
                    ),
                ),
                ("transfer_marked_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_by", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_donations",
                        to="accounts.donorprofile",
                    ),
                ),
            ],
            options={
                "db_table": "money_donations",
            },
        ),
    ]
