# Generated by Django 5.2.15 on 2026-06-14 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("donations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("claim_date", models.DateField()),
                ("claimed_at", models.DateTimeField()),
                ("receiver_lat", models.DecimalField(decimal_places=7, max_digits=10)),
                ("receiver_lng", models.DecimalField(decimal_places=7, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("CLAIMED", "Claimed")], default="CLAIMED", max_length=20
                    ),
                ),
                ("quantity_claimed", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="donations.fooditem",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_claims",
                        to="accounts.restaurantprofile",
                    ),
                ),
            ],
            options={
                "db_table": "food_claims",
                "indexes": [
                    models.Index(
                        fields=["receiver", "claim_date"], name="food_claims_receive_9df14c_idx"
                    ),
                    models.Index(
                        fields=["food", "-claimed_at"], name="food_claims_food_id_a70308_idx"
                    ),
                    models.Index(
                        fields=["restaurant", "claim_date"], name="food_claims_restaur_8fe06e_idx"
                    ),
                ],
            },
        ),
    ]
