# Generated by Django 5.2.15 on 2026-07-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodclaim',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodclaim',
            name='status',
            field=models.CharField(choices=[('CLAIMED', 'Claimed'), ('COLLECTED', 'Collected')], default='CLAIMED', max_length=20),
        ),
    ]
