# Generated by Django 5.2.15 on 2026-07-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_restaurant_detail_profile_gaps'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodclaim',
            name='no_show_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodclaim',
            name='status',
            field=models.CharField(choices=[('CLAIMED', 'Claimed'), ('COLLECTED', 'Collected'), ('NO_SHOW', 'No-show')], default='CLAIMED', max_length=20),
        ),
    ]
