# Generated by Django 5.2.15 on 2026-07-19 06:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_restaurant_detail_profile_gaps'),
        ('claims', '0003_claim_no_show'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimReportReasonOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'claim_report_reason_options',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ClaimReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='claims.foodclaim')),
                ('reported_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_reports', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_reports', to='accounts.restaurantprofile')),
                ('reason_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='claims.claimreportreasonoption')),
            ],
            options={
                'db_table': 'claim_reports',
                'indexes': [models.Index(fields=['restaurant', 'created_at'], name='claim_repor_restaur_7cbc30_idx'), models.Index(fields=['claim', 'created_at'], name='claim_repor_claim_i_a1f0e5_idx'), models.Index(fields=['reported_receiver', 'created_at'], name='claim_repor_reporte_2e6e09_idx')],
            },
        ),
    ]
