# Generated by Django 5.2.15 on 2026-07-21 07:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_restaurant__purge_a_7c2e1a_idx_restaurant__purge_a_84e4e7_idx_and_more'),
        ('claims', '0004_claim_reports'),
        ('donations', '0006_menu_photos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTagOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'review_tag_options',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ClaimReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='claims.foodclaim')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_reviews', to='donations.fooditem')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_reviews', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_reviews', to='accounts.restaurantprofile')),
                ('tags', models.ManyToManyField(blank=True, related_name='reviews', to='claims.reviewtagoption')),
            ],
            options={
                'db_table': 'claim_reviews',
                'indexes': [
                    models.Index(fields=['restaurant', '-created_at'], name='claim_revie_restaur_86b4a8_idx'),
                    models.Index(fields=['receiver', '-created_at'], name='claim_revie_receive_fcf89d_idx'),
                ],
            },
        ),
    ]
