# Generated by Django 5.2.15 on 2026-08-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsettings_alert_no_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='alert_claim_confirmations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='alert_daily_limit_reset',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='alert_new_food_nearby',
            field=models.BooleanField(default=True),
        ),
    ]
